name: Github Page

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Bun (if you still want Bun installed, but Next.js will not use it)
        run: curl -fsSL https://bun.sh/install | bash

      - name: Set up Node.js (since Next.js uses Node.js)
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Set Git identity for commits
        run: |
          git config --global user.name "github-actions[bot]"  # Set the bot's name
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Build project with Next.js
        run: npm run deploy
