name: Github Page

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Bun (if you still want Bun installed, but Next.js will not use it)
        run: curl -fsSL https://bun.sh/install | bash

      - name: Set up Node.js (since Next.js uses Node.js)
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install # Use npm (or yarn) for Next.js

      - name: Set Environment Variables
        env:
          BASE_PATH: /react-texteditor-example
        run: |
          echo "" > .env.local
          echo BASE_PATH=$BASE_PATH >> .env.local

      - name: Build project with Next.js
        run: npm run build # Use Next.js' build command

      - name: Create .nojekyll file
        run: touch ./out/.nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
