name: Gh-Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      my_secret: ${{secrets.ACCESS_TOKEN}}

    steps:
      - uses: actions/checkout@v2 # Only works with v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build web
      - run: |
          cd build
          cd web-deploy
          git config --global user.email king.waterf@gmail.com
          git config --global user.name Karula-k
          git config --global init.defaultBranch main
          git init
          git remote add origin https://${{secrets.ACCESS_TOKEN}}@github.com/Karula-k/Karula-k.github.io.git
          git fetch origin gh-pages
          git switch gh-pages
          cp -R ../web/* .
          git status
          git add .
          # add commit of the previous commit from main
          echo ""
          echo "Committing to gh-pages: ${{ github.event.head_commit.message }}"
          echo ""
          git commit -m "${{ github.event.head_commit.message }}"
          git push origin gh-pages
